### ISSUE TITLE
KeyError: 'cooldown'

### ISSUE THREAD

**Issue by cavrt** [TheDrHax/Twitch-Chat-Downloader#15]
python 3.11.3, tdh-tcd latest

```
C:\Users\MyUser>python -m tcd 1821856251 --directory V:\ --formats srt

Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python311\Lib\site-packages\tcd\__init__.py", line 6, in <module>
    from .twitch import Messages, Channel
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python311\Lib\site-packages\tcd\twitch.py", line 8, in <module>
    from .settings import settings
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python311\Lib\site-packages\tcd\settings.py", line 202, in <module>
    args, unknown_args = _post_init_parser(help=False).parse_known_args()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python311\Lib\site-packages\tcd\settings.py", line 82, in _post_init_parser
    '--cooldown', metavar='msec', type=int, default=settings['cooldown'],
                                                    ~~~~~~~~^^^^^^^^^^^^
KeyError: 'cooldown'
```

**Comment by ghost** [comment]
Copy the `tcd/example.settings.json` file to the working directory. Fixed the issue for me.
